MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
TRAIN:
  n_epochs: &n_epochs 100
  batch_size: 24

  model: &model models.unet.ResnetSuperVision
  model_params: &model_params
    seg_classes: 4
    backbone_arch: resnet34

  train_params:
    name: &name resnet34_768_unet_v6
    model: *model
    model_params: *model_params
    loss: losses.ComboSuperVisionLoss
    loss_params:
      weights:
        bce: 3
        dice: n1
      sv_weight: 0.2
    metrics:
      metrics.HardDiceCoef:
        threshold: 0.5
      metrics.SoftDiceCoef:
        class_id: -1
      metrics.JaccardScore:
        threshold: 0.5

  stages:
    cosine:
      optimizer: optimizer.RAdam
      optimizer_params:
        lr: 0.0001
        weight_decay: 0.00001
      scheduler: CosineAnnealingLR
      scheduler_params:
        T_max: 10
        eta_min: 0.000001
      epochs: *n_epochs

  swa: 0
  data_params:
    empty_mask_increase:
      state: "true"
      start_value: 0.2
      end_value: 1.0
      n_epochs: 50

  dumps:
    path: /home/danil.akhmetov/Projects/Severstal/output/
    weights: weights
    logs: logs

TEST:
  name: *name
  batch_size: 64
  model: *model
  model_params: *model_params
  weights: /home/danil.akhmetov/Projects/Severstal/output/weights




