MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
TRAIN:
  n_epochs: &n_epochs 120
  batch_size: 24

  model: &model models.segmentation_models_pytorch_danil.Unet
  model_params: &model_params
    classes: 4
    encoder_weights: imagenet
    encoder_name: efficientnet-b5
    attention_type: scse
    cls_out: 1

  train_params:
    name: &name smp_efb5_crop_bce_v1
    type: crop
    model: *model
    model_params: *model_params
    loss: losses.ComboSuperVisionLoss
    n_epochs_freeze: 0
    loss_params:
      weights:
        focal: 3
        dice: 1
      sv_weight: 0.1
    metrics:
      metrics.HardDiceCoef:
        threshold: 0.5
      metrics.SoftDiceCoef:
        class_id: -1
      metrics.AccuracyScore:
        threshold: 0.5

  stages:
    cosine:
      optimizer: optimizer.RAdam
      optimizer_params:
        lr: 0.0001
        weight_decay: 0.00001
      scheduler: CosineAnnealingLR
      scheduler_params:
        T_max: 10
        eta_min: 0.000001
      epochs: *n_epochs

  swa: 0
  data_params:
    empty_mask_increase:
      state: "true"
      start_value: 0.05
      end_value: 1.0
      n_epochs: 50

  dumps:
    path: /home/danil.akhmetov/Projects/Severstal/output/
    weights: weights
    logs: logs

TEST:
  name: *name
  type: crop
  # type: full
  batch_size: 64
  model: *model
  model_params: *model_params
  weights: /home/danil.akhmetov/Projects/Severstal/output/weights
  cls_predict: ''
  threshold_cls: 0.95
  TTA: 'false'




