MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
TRAIN:
  n_epochs: &n_epochs 100
  batch_size: 64

  model: &model smp_resnet34_v1
  model_params: &model_params
    seg_classes: 4
    encoder_weights: imagenet
    backbone_arch: resnet34

  train_params:
    name: &name smp_resnet34_crop_v1
    type: crop
    model: *model
    model_params: *model_params
    loss: losses.ComboSuperVisionLoss
    n_epochs_freeze: 10
    loss_params:
      weights:
        bce: 3
        dice: 1
    metrics:
      metrics.HardDiceCoef:
        threshold: 0.5
      metrics.SoftDiceCoef:
        class_id: -1

  stages:
    cosine:
      optimizer: optimizer.RAdam
      optimizer_params:
        lr: 0.000075
        weight_decay: 0.00001
      scheduler: CosineAnnealingLR
      scheduler_params:
        T_max: 10
        eta_min: 0.000001
      epochs: *n_epochs

  swa: 0
  data_params:
    empty_mask_increase:
      state: "true"
      start_value: 0.1
      end_value: 1.0
      n_epochs: 50

  dumps:
    path: /home/danil.akhmetov/Projects/Severstal/output/
    weights: weights
    logs: logs

TEST:
  name: *name
  type: crop
  batch_size: 64
  model: *model
  model_params: *model_params
  weights: /home/danil.akhmetov/Projects/Severstal/output/weights




