MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
DATASETS:
  a: 1
TRAIN:
  n_epochs: &n_epochs 100
  batch_size: 32
  learning_rate: 0.001

  model: &model src.models.unet.ResnetSuperVision
  model_params: &model_params
    seg_classes: 4
    backbone_arch: resnet34

  train_params:
    name: resnet34_768_unet
    model: *model
    model_params: *model_params
#    loss: src.loss.BCEDiceLoss
#    loss_params:
#      weights:
#        bce: 0.5
#        dice: 0.5
    loss: src.losses.ComboSuperVisionLoss
    loss_params:
      weights:
        bce: 3
        dice: 1
      sv_weight: 0.1
    metrics:
      src.metrics.HardDiceCoef:
        threshold: 0.5
      src.metrics.SoftDiceCoef:
        class_id: 1

  stages:
    cosine:
      optimizer: Adam
      optimizer_params:
        lr: 0.0001
        weight_decay: 0.00001
      scheduler: CosineAnnealingLR
      scheduler_params:
        T_max: 8
        eta_min: 0.000001
      epochs: *n_epochs

  swa: 0
  data_params:
    empty_mask_increase:
      state: "true"
      start_value: 0.0
      end_value: 1.0
      n_epochs: 50

  dumps:
    path: /home/danil.akhmetov/Projects/Severstal/output/
    weights: weights
    logs: logs

TEST:
  prefix: "miras_radam"
  batch_size: 64
  weight: ""
  log_path: "/home/danil.akhmetov/Projects/Severstal/output/logs"
  model_path: "/home/danil.akhmetov/Projects/Severstal/output/models"




