MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
DATASETS:
  a: 1
TRAIN:
  n_epochs: 100
  batch_size: 64
  learning_rate: 0.001
  optimizer: "radam"
  weight_decay: 0.00001
  scheduler: "cosine"
  swa: 0
  empty_mask_increase:
    state: "true"
    start_value: 0.0
    end_value: 1.0
    n_epochs: 50
  prefix: "miras_radam_lr1e-3"
  weight: ""
  log_path: "/home/danil.akhmetov/Projects/Severstal/output/logs"
  model_path: "/home/danil.akhmetov/Projects/Severstal/output/models"
TEST:
  prefix: "miras_radam"
  batch_size: 64
  weight: ""
  log_path: "/home/danil.akhmetov/Projects/Severstal/output/logs"
  model_path: "/home/danil.akhmetov/Projects/Severstal/output/models"

