MAIN:
  path_to_project: "/home/danil.akhmetov/Projects/Severstal/"
  path_to_data: "/home/danil.akhmetov/Projects/Severstal/data/"
TRAIN:
  n_epochs: 100
  batch_size: 64
  learning_rate: 0.0001
  optimizer: "radam"
  weight_decay: 0.00001
  scheduler: "cosine"
  swa: 0
  empty_mask_increase:
    state: "false"
    start_value: 0.0
    end_value: 1.0
    n_epochs: 50
  prefix: "efb0"
  weight: ""
  log_path: "/home/danil.akhmetov/Projects/Severstal/output/logs_cls"
  model_path: "/home/danil.akhmetov/Projects/Severstal/output/models_cls"
TEST:
  prefix: "efb0"
  batch_size: 64
  weight: ""
  model_path: "/home/danil.akhmetov/Projects/Severstal/output/models_cls"

